<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LibmemCliTestPackageVersion Condition="'$(LibmemCliTestPackageVersion)' == ''">0.0.0-local</LibmemCliTestPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Libmem.NET"
                      Version="$(LibmemCliTestPackageVersion)" />
  </ItemGroup>
</Project>
